version: '3.1'
services:
    selenium:
        image: selenium/standalone-chrome
        ports:
            - 4444:4444
        environment:
            SE_NODE_OVERRIDE_MAX_SESSIONS: true
            SE_NODE_MAX_SESSIONS: 8
            SE_NODE_SESSION_TIMEOUT: 3600
        networks:
            - airflow
        shm_size: 4gb

    postgres-db:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        networks:
            - airflow
        shm_size: 2gb

    scheduler:
        volumes:
            - ./outputs:/usr/local/airflow/outputs
